variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "instance_type" {}
variable ""public_subnet_1_cidr"" {}
variable "public_subnet_2_cidr" {}
variable "private_app_subnet_1_cidr" {}
variable "private_app_subnet_2_cidr" {}
variable "private_data_subnet_1_cidr" {}
variable "private_data_subnet_2_cidr" {}
